// Exact IMD Gridded Rainfall (0.25° NetCDF) extracted for Maharashtra Kharif Season (June-October)
// Generated by process_all_rainfall.py from verified IMD NetCDF grids 2015–2022
// Output/imd_district_kharif_rainfall_2015_2022.csv

export interface ImdDistrictRainfallRecord {
  district: string;
  year: string; // e.g. "2015-16"
  yearInt: number; // e.g. 2015
  kharifRainfallMm: number;
  gridPointsUsed: number;
}

export type ImdRainfallRecord = ImdDistrictRainfallRecord;

export const IMD_DISTRICT_KHARIF_RAINFALL: ImdDistrictRainfallRecord[] = [
  // Ahilyanagar (Ahmednagar)
  { district: "Ahilyanagar", year: "2015-16", yearInt: 2015, kharifRainfallMm: 394.5, gridPointsUsed: 22 },
  { district: "Ahilyanagar", year: "2016-17", yearInt: 2016, kharifRainfallMm: 654.7, gridPointsUsed: 22 },
  { district: "Ahilyanagar", year: "2017-18", yearInt: 2017, kharifRainfallMm: 788.8, gridPointsUsed: 22 },
  { district: "Ahilyanagar", year: "2018-19", yearInt: 2018, kharifRainfallMm: 357.4, gridPointsUsed: 22 },
  { district: "Ahilyanagar", year: "2019-20", yearInt: 2019, kharifRainfallMm: 783.4, gridPointsUsed: 22 },
  { district: "Ahilyanagar", year: "2020-21", yearInt: 2020, kharifRainfallMm: 1014.8, gridPointsUsed: 22 },
  { district: "Ahilyanagar", year: "2021-22", yearInt: 2021, kharifRainfallMm: 744.2, gridPointsUsed: 22 },
  { district: "Ahilyanagar", year: "2022-23", yearInt: 2022, kharifRainfallMm: 903.7, gridPointsUsed: 22 },

  // Amravati
  { district: "Amravati", year: "2015-16", yearInt: 2015, kharifRainfallMm: 740.2, gridPointsUsed: 16 },
  { district: "Amravati", year: "2016-17", yearInt: 2016, kharifRainfallMm: 961.1, gridPointsUsed: 16 },
  { district: "Amravati", year: "2017-18", yearInt: 2017, kharifRainfallMm: 637.4, gridPointsUsed: 16 },
  { district: "Amravati", year: "2018-19", yearInt: 2018, kharifRainfallMm: 608.9, gridPointsUsed: 16 },
  { district: "Amravati", year: "2019-20", yearInt: 2019, kharifRainfallMm: 952.8, gridPointsUsed: 16 },
  { district: "Amravati", year: "2020-21", yearInt: 2020, kharifRainfallMm: 738.4, gridPointsUsed: 16 },
  { district: "Amravati", year: "2021-22", yearInt: 2021, kharifRainfallMm: 880.2, gridPointsUsed: 16 },
  { district: "Amravati", year: "2022-23", yearInt: 2022, kharifRainfallMm: 1101.1, gridPointsUsed: 16 },

  // Beed
  { district: "Beed", year: "2015-16", yearInt: 2015, kharifRainfallMm: 328.5, gridPointsUsed: 15 },
  { district: "Beed", year: "2016-17", yearInt: 2016, kharifRainfallMm: 897.8, gridPointsUsed: 15 },
  { district: "Beed", year: "2017-18", yearInt: 2017, kharifRainfallMm: 773.1, gridPointsUsed: 15 },
  { district: "Beed", year: "2018-19", yearInt: 2018, kharifRainfallMm: 394.7, gridPointsUsed: 15 },
  { district: "Beed", year: "2019-20", yearInt: 2019, kharifRainfallMm: 759.4, gridPointsUsed: 15 },
  { district: "Beed", year: "2020-21", yearInt: 2020, kharifRainfallMm: 961.1, gridPointsUsed: 15 },
  { district: "Beed", year: "2021-22", yearInt: 2021, kharifRainfallMm: 1077.3, gridPointsUsed: 15 },
  { district: "Beed", year: "2022-23", yearInt: 2022, kharifRainfallMm: 775.0, gridPointsUsed: 15 },

  // Bhandara
  { district: "Bhandara", year: "2015-16", yearInt: 2015, kharifRainfallMm: 1095.9, gridPointsUsed: 6 },
  { district: "Bhandara", year: "2016-17", yearInt: 2016, kharifRainfallMm: 1141.6, gridPointsUsed: 6 },
  { district: "Bhandara", year: "2017-18", yearInt: 2017, kharifRainfallMm: 795.1, gridPointsUsed: 6 },
  { district: "Bhandara", year: "2018-19", yearInt: 2018, kharifRainfallMm: 1050.4, gridPointsUsed: 6 },
  { district: "Bhandara", year: "2019-20", yearInt: 2019, kharifRainfallMm: 1196.7, gridPointsUsed: 6 },
  { district: "Bhandara", year: "2020-21", yearInt: 2020, kharifRainfallMm: 1132.3, gridPointsUsed: 6 },
  { district: "Bhandara", year: "2021-22", yearInt: 2021, kharifRainfallMm: 1118.1, gridPointsUsed: 6 },
  { district: "Bhandara", year: "2022-23", yearInt: 2022, kharifRainfallMm: 1729.6, gridPointsUsed: 6 },

  // Buldhana
  { district: "Buldhana", year: "2015-16", yearInt: 2015, kharifRainfallMm: 582.0, gridPointsUsed: 15 },
  { district: "Buldhana", year: "2016-17", yearInt: 2016, kharifRainfallMm: 798.4, gridPointsUsed: 15 },
  { district: "Buldhana", year: "2017-18", yearInt: 2017, kharifRainfallMm: 689.4, gridPointsUsed: 15 },
  { district: "Buldhana", year: "2018-19", yearInt: 2018, kharifRainfallMm: 514.3, gridPointsUsed: 15 },
  { district: "Buldhana", year: "2019-20", yearInt: 2019, kharifRainfallMm: 785.6, gridPointsUsed: 15 },
  { district: "Buldhana", year: "2020-21", yearInt: 2020, kharifRainfallMm: 710.2, gridPointsUsed: 15 },
  { district: "Buldhana", year: "2021-22", yearInt: 2021, kharifRainfallMm: 857.6, gridPointsUsed: 15 },
  { district: "Buldhana", year: "2022-23", yearInt: 2022, kharifRainfallMm: 797.0, gridPointsUsed: 15 },

  // Chandrapur
  { district: "Chandrapur", year: "2015-16", yearInt: 2015, kharifRainfallMm: 1020.1, gridPointsUsed: 14 },
  { district: "Chandrapur", year: "2016-17", yearInt: 2016, kharifRainfallMm: 1570.2, gridPointsUsed: 14 },
  { district: "Chandrapur", year: "2017-18", yearInt: 2017, kharifRainfallMm: 903.2, gridPointsUsed: 14 },
  { district: "Chandrapur", year: "2018-19", yearInt: 2018, kharifRainfallMm: 1087.3, gridPointsUsed: 14 },
  { district: "Chandrapur", year: "2019-20", yearInt: 2019, kharifRainfallMm: 1512.1, gridPointsUsed: 14 },
  { district: "Chandrapur", year: "2020-21", yearInt: 2020, kharifRainfallMm: 959.8, gridPointsUsed: 14 },
  { district: "Chandrapur", year: "2021-22", yearInt: 2021, kharifRainfallMm: 1097.5, gridPointsUsed: 14 },
  { district: "Chandrapur", year: "2022-23", yearInt: 2022, kharifRainfallMm: 1511.0, gridPointsUsed: 14 },

  // Chhatrapati Sambhajinagar (Aurangabad)
  { district: "Chhatrapati Sambhajinagar", year: "2015-16", yearInt: 2015, kharifRainfallMm: 505.5, gridPointsUsed: 15 },
  { district: "Chhatrapati Sambhajinagar", year: "2016-17", yearInt: 2016, kharifRainfallMm: 706.2, gridPointsUsed: 15 },
  { district: "Chhatrapati Sambhajinagar", year: "2017-18", yearInt: 2017, kharifRainfallMm: 688.2, gridPointsUsed: 15 },
  { district: "Chhatrapati Sambhajinagar", year: "2018-19", yearInt: 2018, kharifRainfallMm: 420.5, gridPointsUsed: 15 },
  { district: "Chhatrapati Sambhajinagar", year: "2019-20", yearInt: 2019, kharifRainfallMm: 795.8, gridPointsUsed: 15 },
  { district: "Chhatrapati Sambhajinagar", year: "2020-21", yearInt: 2020, kharifRainfallMm: 967.3, gridPointsUsed: 15 },
  { district: "Chhatrapati Sambhajinagar", year: "2021-22", yearInt: 2021, kharifRainfallMm: 1074.7, gridPointsUsed: 15 },
  { district: "Chhatrapati Sambhajinagar", year: "2022-23", yearInt: 2022, kharifRainfallMm: 861.9, gridPointsUsed: 15 },

  // Dharashiv (Osmanabad)
  { district: "Dharashiv", year: "2015-16", yearInt: 2015, kharifRainfallMm: 370.0, gridPointsUsed: 12 },
  { district: "Dharashiv", year: "2016-17", yearInt: 2016, kharifRainfallMm: 940.7, gridPointsUsed: 12 },
  { district: "Dharashiv", year: "2017-18", yearInt: 2017, kharifRainfallMm: 940.1, gridPointsUsed: 12 },
  { district: "Dharashiv", year: "2018-19", yearInt: 2018, kharifRainfallMm: 567.5, gridPointsUsed: 12 },
  { district: "Dharashiv", year: "2019-20", yearInt: 2019, kharifRainfallMm: 761.4, gridPointsUsed: 12 },
  { district: "Dharashiv", year: "2020-21", yearInt: 2020, kharifRainfallMm: 1006.6, gridPointsUsed: 12 },
  { district: "Dharashiv", year: "2021-22", yearInt: 2021, kharifRainfallMm: 995.4, gridPointsUsed: 12 },
  { district: "Dharashiv", year: "2022-23", yearInt: 2022, kharifRainfallMm: 925.5, gridPointsUsed: 12 },

  // Dhule
  { district: "Dhule", year: "2015-16", yearInt: 2015, kharifRainfallMm: 502.3, gridPointsUsed: 9 },
  { district: "Dhule", year: "2016-17", yearInt: 2016, kharifRainfallMm: 548.0, gridPointsUsed: 9 },
  { district: "Dhule", year: "2017-18", yearInt: 2017, kharifRainfallMm: 607.8, gridPointsUsed: 9 },
  { district: "Dhule", year: "2018-19", yearInt: 2018, kharifRainfallMm: 470.9, gridPointsUsed: 9 },
  { district: "Dhule", year: "2019-20", yearInt: 2019, kharifRainfallMm: 1020.8, gridPointsUsed: 9 },
  { district: "Dhule", year: "2020-21", yearInt: 2020, kharifRainfallMm: 870.7, gridPointsUsed: 9 },
  { district: "Dhule", year: "2021-22", yearInt: 2021, kharifRainfallMm: 829.0, gridPointsUsed: 9 },
  { district: "Dhule", year: "2022-23", yearInt: 2022, kharifRainfallMm: 849.2, gridPointsUsed: 9 },

  // Gadchiroli
  { district: "Gadchiroli", year: "2015-16", yearInt: 2015, kharifRainfallMm: 1070.9, gridPointsUsed: 7 },
  { district: "Gadchiroli", year: "2016-17", yearInt: 2016, kharifRainfallMm: 1739.1, gridPointsUsed: 7 },
  { district: "Gadchiroli", year: "2017-18", yearInt: 2017, kharifRainfallMm: 1061.2, gridPointsUsed: 7 },
  { district: "Gadchiroli", year: "2018-19", yearInt: 2018, kharifRainfallMm: 1385.4, gridPointsUsed: 7 },
  { district: "Gadchiroli", year: "2019-20", yearInt: 2019, kharifRainfallMm: 1934.5, gridPointsUsed: 7 },
  { district: "Gadchiroli", year: "2020-21", yearInt: 2020, kharifRainfallMm: 1340.3, gridPointsUsed: 7 },
  { district: "Gadchiroli", year: "2021-22", yearInt: 2021, kharifRainfallMm: 1083.8, gridPointsUsed: 7 },
  { district: "Gadchiroli", year: "2022-23", yearInt: 2022, kharifRainfallMm: 1808.5, gridPointsUsed: 7 },

  // Gondia
  { district: "Gondia", year: "2015-16", yearInt: 2015, kharifRainfallMm: 1196.7, gridPointsUsed: 3 },
  { district: "Gondia", year: "2016-17", yearInt: 2016, kharifRainfallMm: 1333.9, gridPointsUsed: 3 },
  { district: "Gondia", year: "2017-18", yearInt: 2017, kharifRainfallMm: 937.4, gridPointsUsed: 3 },
  { district: "Gondia", year: "2018-19", yearInt: 2018, kharifRainfallMm: 1119.5, gridPointsUsed: 3 },
  { district: "Gondia", year: "2019-20", yearInt: 2019, kharifRainfallMm: 1432.5, gridPointsUsed: 3 },
  { district: "Gondia", year: "2020-21", yearInt: 2020, kharifRainfallMm: 1144.2, gridPointsUsed: 3 },
  { district: "Gondia", year: "2021-22", yearInt: 2021, kharifRainfallMm: 1102.7, gridPointsUsed: 3 },
  { district: "Gondia", year: "2022-23", yearInt: 2022, kharifRainfallMm: 1727.8, gridPointsUsed: 3 },

  // Jalna
  { district: "Jalna", year: "2015-16", yearInt: 2015, kharifRainfallMm: 475.7, gridPointsUsed: 9 },
  { district: "Jalna", year: "2016-17", yearInt: 2016, kharifRainfallMm: 891.8, gridPointsUsed: 9 },
  { district: "Jalna", year: "2017-18", yearInt: 2017, kharifRainfallMm: 671.7, gridPointsUsed: 9 },
  { district: "Jalna", year: "2018-19", yearInt: 2018, kharifRainfallMm: 436.0, gridPointsUsed: 9 },
  { district: "Jalna", year: "2019-20", yearInt: 2019, kharifRainfallMm: 795.2, gridPointsUsed: 9 },
  { district: "Jalna", year: "2020-21", yearInt: 2020, kharifRainfallMm: 866.0, gridPointsUsed: 9 },
  { district: "Jalna", year: "2021-22", yearInt: 2021, kharifRainfallMm: 1135.6, gridPointsUsed: 9 },
  { district: "Jalna", year: "2022-23", yearInt: 2022, kharifRainfallMm: 749.6, gridPointsUsed: 9 },

  // Kolhapur
  { district: "Kolhapur", year: "2015-16", yearInt: 2015, kharifRainfallMm: 602.0, gridPointsUsed: 9 },
  { district: "Kolhapur", year: "2016-17", yearInt: 2016, kharifRainfallMm: 1181.6, gridPointsUsed: 9 },
  { district: "Kolhapur", year: "2017-18", yearInt: 2017, kharifRainfallMm: 1191.7, gridPointsUsed: 9 },
  { district: "Kolhapur", year: "2018-19", yearInt: 2018, kharifRainfallMm: 1269.0, gridPointsUsed: 9 },
  { district: "Kolhapur", year: "2019-20", yearInt: 2019, kharifRainfallMm: 2273.5, gridPointsUsed: 9 },
  { district: "Kolhapur", year: "2020-21", yearInt: 2020, kharifRainfallMm: 1644.5, gridPointsUsed: 9 },
  { district: "Kolhapur", year: "2021-22", yearInt: 2021, kharifRainfallMm: 1410.3, gridPointsUsed: 9 },
  { district: "Kolhapur", year: "2022-23", yearInt: 2022, kharifRainfallMm: 1510.4, gridPointsUsed: 9 },

  // Latur
  { district: "Latur", year: "2015-16", yearInt: 2015, kharifRainfallMm: 404.9, gridPointsUsed: 9 },
  { district: "Latur", year: "2016-17", yearInt: 2016, kharifRainfallMm: 1065.6, gridPointsUsed: 9 },
  { district: "Latur", year: "2017-18", yearInt: 2017, kharifRainfallMm: 800.0, gridPointsUsed: 9 },
  { district: "Latur", year: "2018-19", yearInt: 2018, kharifRainfallMm: 590.7, gridPointsUsed: 9 },
  { district: "Latur", year: "2019-20", yearInt: 2019, kharifRainfallMm: 859.5, gridPointsUsed: 9 },
  { district: "Latur", year: "2020-21", yearInt: 2020, kharifRainfallMm: 985.6, gridPointsUsed: 9 },
  { district: "Latur", year: "2021-22", yearInt: 2021, kharifRainfallMm: 1032.4, gridPointsUsed: 9 },
  { district: "Latur", year: "2022-23", yearInt: 2022, kharifRainfallMm: 1037.4, gridPointsUsed: 9 },

  // Nagpur
  { district: "Nagpur", year: "2015-16", yearInt: 2015, kharifRainfallMm: 1043.9, gridPointsUsed: 15 },
  { district: "Nagpur", year: "2016-17", yearInt: 2016, kharifRainfallMm: 918.7, gridPointsUsed: 15 },
  { district: "Nagpur", year: "2017-18", yearInt: 2017, kharifRainfallMm: 921.6, gridPointsUsed: 15 },
  { district: "Nagpur", year: "2018-19", yearInt: 2018, kharifRainfallMm: 970.8, gridPointsUsed: 15 },
  { district: "Nagpur", year: "2019-20", yearInt: 2019, kharifRainfallMm: 1220.2, gridPointsUsed: 15 },
  { district: "Nagpur", year: "2020-21", yearInt: 2020, kharifRainfallMm: 1045.2, gridPointsUsed: 15 },
  { district: "Nagpur", year: "2021-22", yearInt: 2021, kharifRainfallMm: 1080.5, gridPointsUsed: 15 },
  { district: "Nagpur", year: "2022-23", yearInt: 2022, kharifRainfallMm: 1582.2, gridPointsUsed: 15 },

  // Nanded
  { district: "Nanded", year: "2015-16", yearInt: 2015, kharifRainfallMm: 521.7, gridPointsUsed: 15 },
  { district: "Nanded", year: "2016-17", yearInt: 2016, kharifRainfallMm: 1206.3, gridPointsUsed: 15 },
  { district: "Nanded", year: "2017-18", yearInt: 2017, kharifRainfallMm: 781.7, gridPointsUsed: 15 },
  { district: "Nanded", year: "2018-19", yearInt: 2018, kharifRainfallMm: 891.9, gridPointsUsed: 15 },
  { district: "Nanded", year: "2019-20", yearInt: 2019, kharifRainfallMm: 1031.3, gridPointsUsed: 15 },
  { district: "Nanded", year: "2020-21", yearInt: 2020, kharifRainfallMm: 1052.6, gridPointsUsed: 15 },
  { district: "Nanded", year: "2021-22", yearInt: 2021, kharifRainfallMm: 1287.1, gridPointsUsed: 15 },
  { district: "Nanded", year: "2022-23", yearInt: 2022, kharifRainfallMm: 1421.7, gridPointsUsed: 15 },

  // Nandurbar
  { district: "Nandurbar", year: "2015-16", yearInt: 2015, kharifRainfallMm: 636.9, gridPointsUsed: 7 },
  { district: "Nandurbar", year: "2016-17", yearInt: 2016, kharifRainfallMm: 696.4, gridPointsUsed: 7 },
  { district: "Nandurbar", year: "2017-18", yearInt: 2017, kharifRainfallMm: 689.0, gridPointsUsed: 7 },
  { district: "Nandurbar", year: "2018-19", yearInt: 2018, kharifRainfallMm: 522.2, gridPointsUsed: 7 },
  { district: "Nandurbar", year: "2019-20", yearInt: 2019, kharifRainfallMm: 1291.7, gridPointsUsed: 7 },
  { district: "Nandurbar", year: "2020-21", yearInt: 2020, kharifRainfallMm: 917.7, gridPointsUsed: 7 },
  { district: "Nandurbar", year: "2021-22", yearInt: 2021, kharifRainfallMm: 799.5, gridPointsUsed: 7 },
  { district: "Nandurbar", year: "2022-23", yearInt: 2022, kharifRainfallMm: 914.6, gridPointsUsed: 7 },

  // Nashik
  { district: "Nashik", year: "2015-16", yearInt: 2015, kharifRainfallMm: 590.3, gridPointsUsed: 22 },
  { district: "Nashik", year: "2016-17", yearInt: 2016, kharifRainfallMm: 937.7, gridPointsUsed: 22 },
  { district: "Nashik", year: "2017-18", yearInt: 2017, kharifRainfallMm: 1041.4, gridPointsUsed: 22 },
  { district: "Nashik", year: "2018-19", yearInt: 2018, kharifRainfallMm: 686.4, gridPointsUsed: 22 },
  { district: "Nashik", year: "2019-20", yearInt: 2019, kharifRainfallMm: 1276.7, gridPointsUsed: 22 },
  { district: "Nashik", year: "2020-21", yearInt: 2020, kharifRainfallMm: 1086.7, gridPointsUsed: 22 },
  { district: "Nashik", year: "2021-22", yearInt: 2021, kharifRainfallMm: 1017.0, gridPointsUsed: 22 },
  { district: "Nashik", year: "2022-23", yearInt: 2022, kharifRainfallMm: 1244.7, gridPointsUsed: 22 },

  // Palghar
  { district: "Palghar", year: "2015-16", yearInt: 2015, kharifRainfallMm: 1806.6, gridPointsUsed: 8 },
  { district: "Palghar", year: "2016-17", yearInt: 2016, kharifRainfallMm: 3028.8, gridPointsUsed: 8 },
  { district: "Palghar", year: "2017-18", yearInt: 2017, kharifRainfallMm: 3338.8, gridPointsUsed: 8 },
  { district: "Palghar", year: "2018-19", yearInt: 2018, kharifRainfallMm: 2558.9, gridPointsUsed: 8 },
  { district: "Palghar", year: "2019-20", yearInt: 2019, kharifRainfallMm: 4254.7, gridPointsUsed: 8 },
  { district: "Palghar", year: "2020-21", yearInt: 2020, kharifRainfallMm: 2819.6, gridPointsUsed: 8 },
  { district: "Palghar", year: "2021-22", yearInt: 2021, kharifRainfallMm: 2915.5, gridPointsUsed: 8 },
  { district: "Palghar", year: "2022-23", yearInt: 2022, kharifRainfallMm: 3519.0, gridPointsUsed: 8 },

  // Parbhani
  { district: "Parbhani", year: "2015-16", yearInt: 2015, kharifRainfallMm: 397.1, gridPointsUsed: 10 },
  { district: "Parbhani", year: "2016-17", yearInt: 2016, kharifRainfallMm: 959.2, gridPointsUsed: 10 },
  { district: "Parbhani", year: "2017-18", yearInt: 2017, kharifRainfallMm: 691.0, gridPointsUsed: 10 },
  { district: "Parbhani", year: "2018-19", yearInt: 2018, kharifRainfallMm: 616.3, gridPointsUsed: 10 },
  { district: "Parbhani", year: "2019-20", yearInt: 2019, kharifRainfallMm: 808.1, gridPointsUsed: 10 },
  { district: "Parbhani", year: "2020-21", yearInt: 2020, kharifRainfallMm: 925.5, gridPointsUsed: 10 },
  { district: "Parbhani", year: "2021-22", yearInt: 2021, kharifRainfallMm: 1202.2, gridPointsUsed: 10 },
  { district: "Parbhani", year: "2022-23", yearInt: 2022, kharifRainfallMm: 867.3, gridPointsUsed: 10 },

  // Pune
  { district: "Pune", year: "2015-16", yearInt: 2015, kharifRainfallMm: 558.5, gridPointsUsed: 19 },
  { district: "Pune", year: "2016-17", yearInt: 2016, kharifRainfallMm: 778.4, gridPointsUsed: 19 },
  { district: "Pune", year: "2017-18", yearInt: 2017, kharifRainfallMm: 950.6, gridPointsUsed: 19 },
  { district: "Pune", year: "2018-19", yearInt: 2018, kharifRainfallMm: 569.4, gridPointsUsed: 19 },
  { district: "Pune", year: "2019-20", yearInt: 2019, kharifRainfallMm: 1318.5, gridPointsUsed: 19 },
  { district: "Pune", year: "2020-21", yearInt: 2020, kharifRainfallMm: 1064.0, gridPointsUsed: 19 },
  { district: "Pune", year: "2021-22", yearInt: 2021, kharifRainfallMm: 675.3, gridPointsUsed: 19 },
  { district: "Pune", year: "2022-23", yearInt: 2022, kharifRainfallMm: 1033.6, gridPointsUsed: 19 },

  // Raigad
  { district: "Raigad", year: "2015-16", yearInt: 2015, kharifRainfallMm: 2395.9, gridPointsUsed: 9 },
  { district: "Raigad", year: "2016-17", yearInt: 2016, kharifRainfallMm: 3946.0, gridPointsUsed: 9 },
  { district: "Raigad", year: "2017-18", yearInt: 2017, kharifRainfallMm: 3964.8, gridPointsUsed: 9 },
  { district: "Raigad", year: "2018-19", yearInt: 2018, kharifRainfallMm: 3379.8, gridPointsUsed: 9 },
  { district: "Raigad", year: "2019-20", yearInt: 2019, kharifRainfallMm: 5431.1, gridPointsUsed: 9 },
  { district: "Raigad", year: "2020-21", yearInt: 2020, kharifRainfallMm: 3779.8, gridPointsUsed: 9 },
  { district: "Raigad", year: "2021-22", yearInt: 2021, kharifRainfallMm: 3464.9, gridPointsUsed: 9 },
  { district: "Raigad", year: "2022-23", yearInt: 2022, kharifRainfallMm: 3636.9, gridPointsUsed: 9 },

  // Ratnagiri
  { district: "Ratnagiri", year: "2015-16", yearInt: 2015, kharifRainfallMm: 2056.8, gridPointsUsed: 11 },
  { district: "Ratnagiri", year: "2016-17", yearInt: 2016, kharifRainfallMm: 3850.5, gridPointsUsed: 11 },
  { district: "Ratnagiri", year: "2017-18", yearInt: 2017, kharifRainfallMm: 3290.2, gridPointsUsed: 11 },
  { district: "Ratnagiri", year: "2018-19", yearInt: 2018, kharifRainfallMm: 3261.3, gridPointsUsed: 11 },
  { district: "Ratnagiri", year: "2019-20", yearInt: 2019, kharifRainfallMm: 4975.2, gridPointsUsed: 11 },
  { district: "Ratnagiri", year: "2020-21", yearInt: 2020, kharifRainfallMm: 3991.8, gridPointsUsed: 11 },
  { district: "Ratnagiri", year: "2021-22", yearInt: 2021, kharifRainfallMm: 4034.7, gridPointsUsed: 11 },
  { district: "Ratnagiri", year: "2022-23", yearInt: 2022, kharifRainfallMm: 3707.0, gridPointsUsed: 11 },

  // Sangli
  { district: "Sangli", year: "2015-16", yearInt: 2015, kharifRainfallMm: 428.3, gridPointsUsed: 11 },
  { district: "Sangli", year: "2016-17", yearInt: 2016, kharifRainfallMm: 708.4, gridPointsUsed: 11 },
  { district: "Sangli", year: "2017-18", yearInt: 2017, kharifRainfallMm: 701.1, gridPointsUsed: 11 },
  { district: "Sangli", year: "2018-19", yearInt: 2018, kharifRainfallMm: 474.2, gridPointsUsed: 11 },
  { district: "Sangli", year: "2019-20", yearInt: 2019, kharifRainfallMm: 1066.8, gridPointsUsed: 11 },
  { district: "Sangli", year: "2020-21", yearInt: 2020, kharifRainfallMm: 1019.6, gridPointsUsed: 11 },
  { district: "Sangli", year: "2021-22", yearInt: 2021, kharifRainfallMm: 764.5, gridPointsUsed: 11 },
  { district: "Sangli", year: "2022-23", yearInt: 2022, kharifRainfallMm: 852.2, gridPointsUsed: 11 },

  // Satara
  { district: "Satara", year: "2015-16", yearInt: 2015, kharifRainfallMm: 480.0, gridPointsUsed: 16 },
  { district: "Satara", year: "2016-17", yearInt: 2016, kharifRainfallMm: 766.3, gridPointsUsed: 16 },
  { district: "Satara", year: "2017-18", yearInt: 2017, kharifRainfallMm: 752.6, gridPointsUsed: 16 },
  { district: "Satara", year: "2018-19", yearInt: 2018, kharifRainfallMm: 534.6, gridPointsUsed: 16 },
  { district: "Satara", year: "2019-20", yearInt: 2019, kharifRainfallMm: 1201.5, gridPointsUsed: 16 },
  { district: "Satara", year: "2020-21", yearInt: 2020, kharifRainfallMm: 1058.6, gridPointsUsed: 16 },
  { district: "Satara", year: "2021-22", yearInt: 2021, kharifRainfallMm: 829.4, gridPointsUsed: 16 },
  { district: "Satara", year: "2022-23", yearInt: 2022, kharifRainfallMm: 848.5, gridPointsUsed: 16 },

  // Sindhudurg
  { district: "Sindhudurg", year: "2015-16", yearInt: 2015, kharifRainfallMm: 2062.3, gridPointsUsed: 9 },
  { district: "Sindhudurg", year: "2016-17", yearInt: 2016, kharifRainfallMm: 3403.2, gridPointsUsed: 9 },
  { district: "Sindhudurg", year: "2017-18", yearInt: 2017, kharifRainfallMm: 3185.2, gridPointsUsed: 9 },
  { district: "Sindhudurg", year: "2018-19", yearInt: 2018, kharifRainfallMm: 3284.3, gridPointsUsed: 9 },
  { district: "Sindhudurg", year: "2019-20", yearInt: 2019, kharifRainfallMm: 5122.0, gridPointsUsed: 9 },
  { district: "Sindhudurg", year: "2020-21", yearInt: 2020, kharifRainfallMm: 4674.3, gridPointsUsed: 9 },
  { district: "Sindhudurg", year: "2021-22", yearInt: 2021, kharifRainfallMm: 4065.2, gridPointsUsed: 9 },
  { district: "Sindhudurg", year: "2022-23", yearInt: 2022, kharifRainfallMm: 3695.0, gridPointsUsed: 9 },

  // Solapur
  { district: "Solapur", year: "2015-16", yearInt: 2015, kharifRainfallMm: 313.3, gridPointsUsed: 22 },
  { district: "Solapur", year: "2016-17", yearInt: 2016, kharifRainfallMm: 593.5, gridPointsUsed: 22 },
  { district: "Solapur", year: "2017-18", yearInt: 2017, kharifRainfallMm: 770.6, gridPointsUsed: 22 },
  { district: "Solapur", year: "2018-19", yearInt: 2018, kharifRainfallMm: 317.3, gridPointsUsed: 22 },
  { district: "Solapur", year: "2019-20", yearInt: 2019, kharifRainfallMm: 604.4, gridPointsUsed: 22 },
  { district: "Solapur", year: "2020-21", yearInt: 2020, kharifRainfallMm: 848.1, gridPointsUsed: 22 },
  { district: "Solapur", year: "2021-22", yearInt: 2021, kharifRainfallMm: 697.2, gridPointsUsed: 22 },
  { district: "Solapur", year: "2022-23", yearInt: 2022, kharifRainfallMm: 699.5, gridPointsUsed: 22 },

  // Thane
  { district: "Thane", year: "2015-16", yearInt: 2015, kharifRainfallMm: 1767.7, gridPointsUsed: 5 },
  { district: "Thane", year: "2016-17", yearInt: 2016, kharifRainfallMm: 2570.6, gridPointsUsed: 5 },
  { district: "Thane", year: "2017-18", yearInt: 2017, kharifRainfallMm: 3257.9, gridPointsUsed: 5 },
  { district: "Thane", year: "2018-19", yearInt: 2018, kharifRainfallMm: 2329.2, gridPointsUsed: 5 },
  { district: "Thane", year: "2019-20", yearInt: 2019, kharifRainfallMm: 3791.1, gridPointsUsed: 5 },
  { district: "Thane", year: "2020-21", yearInt: 2020, kharifRainfallMm: 2357.4, gridPointsUsed: 5 },
  { district: "Thane", year: "2021-22", yearInt: 2021, kharifRainfallMm: 2462.0, gridPointsUsed: 5 },
  { district: "Thane", year: "2022-23", yearInt: 2022, kharifRainfallMm: 3237.7, gridPointsUsed: 5 },

  // Additional 6 districts extracted in test run (Washim, Akola, Hingoli, Jalgaon, Wardha, Yavatmal)
  { district: "Washim", year: "2015-16", yearInt: 2015, kharifRainfallMm: 667.7, gridPointsUsed: 6 },
  { district: "Akola", year: "2015-16", yearInt: 2015, kharifRainfallMm: 700.2, gridPointsUsed: 7 },
  { district: "Hingoli", year: "2015-16", yearInt: 2015, kharifRainfallMm: 606.9, gridPointsUsed: 6 },
  { district: "Jalgaon", year: "2015-16", yearInt: 2015, kharifRainfallMm: 444.5, gridPointsUsed: 15 },
  { district: "Wardha", year: "2015-16", yearInt: 2015, kharifRainfallMm: 932.4, gridPointsUsed: 7 },
  { district: "Yavatmal", year: "2015-16", yearInt: 2015, kharifRainfallMm: 791.9, gridPointsUsed: 20 },
];

export const IMD_RAINFALL_2015_2022 = IMD_DISTRICT_KHARIF_RAINFALL;

